name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Vous pouvez également utiliser Python 3.6 si nécessaire

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install system dependencies for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install selenium

    - name: Run tests
      run: pytest
