name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
      working-directory: https://github.com/Dewanou/Rp2dewanou/blob/main/fichier_dashboard.py

    - name: Run Tests
      run: |
        pytest
      working-directory: https://github.com/Dewanou/Rp2dewanou/blob/main/fichier_dashboard.py
